### PR TITLE
feat(project): add TypeScript definitions

### PR DESCRIPTION
**Pull request by nikeee**
This PR adds type definitions to the NPM package. Then TS users are installing this package, they should get type checking automatically.

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your PR.

We'd be happy to merge this if you apply a few minor adjustments:

* Adopt to our commit message style: `feat(project): add TypeScript definitions`
* Don't publish `lib/*`, instead copy the file to the `dist` folder during bundling, i.e. by using [rollup-plugin-copy](https://github.com/meuter/rollup-plugin-copy).

**Comment by nikeee** [comment]
I've updated this PR. If it's okay, I'll update the other ones as well.

**Comment by nikku** [comment]
> If it's okay, I'll update the other ones as well.

Yes, please do so.

**Comment by nikeee** [comment]
Done

**Comment by nikku** [comment]
Merged via 6b780f664e4eedda2e8a5f0b532d065267eaba3c.

Unfortunately `rollup-plugin-copy` was unstable for me and on CI. I went for manually copying the type definitions via `cpx`.

Merged via https://github.com/bpmn-io/tiny-svg/commit/6b780f664e4eedda2e8a5f0b532d065267eaba3c.

**Comment by nikku** [comment]
Released as `v2.1.0`.

**Pull request closed without merging**
